name: GAMS, Python and .NET on Debian

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push gams-aspnet-on-debian
      id: docker_build_gams_aspnet_on_debian
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jasdefer/gams-aspnet-on-debian
        file: Dockerfiles/gams-aspnet-on-debian
    - name: Image digest gams-aspnet-python-on-debian
      run: echo ${{ steps.docker_build.outputs.digest }}
    - name: Build and push
      id: docker_build_gams_aspnet_python_on_debian
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: jasdefer/gams-aspnet-python-on-debian
        file: Dockerfiles/gams-aspnet-python-on-debian
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}      
